language: java
dist: xenial
jdk:
- openjdk8
- openjdk11
addons:
  apt:
    packages:
    - libturbojpeg
    - libxml2-utils
before_script:
- PROJECT_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)
- wget https://github.com/uclouvain/openjpeg/releases/download/v2.3.0/openjpeg-v2.3.0-linux-x86_64.tar.gz -O /tmp/openjpeg.tar.gz
- tar -xvf /tmp/openjpeg.tar.gz
- export LD_LIBRARY_PATH=$PWD/openjpeg-v2.3.0-linux-x86_64/lib:$LD_LIBRARY_PATH
after_success:
- bash <(curl -s https://codecov.io/bash) -t ea2cc58d-57f1-4653-89eb-8ab0b7c3ab7f
- if [[ "$PROJECT_VERSION" == *SNAPSHOT ]]; then mvn deploy -B -DskipTests=true --settings settings.xml; fi
deploy:
  provider: releases
  api_key:
    secure: O6V2M4M/yHl6rXU9pAXOmQR0R4bJ3O0Vjh3mHR+ZSvMrqSk0CYyN4D+t6xm8+9aS+eAU6Le/mujvcIMUFcccmtmCNm7VNcHTVjRojyWZk0a9ZPqaRkUG4UGo6H/9uqwuHl9Ew+WiVFOGGWqTKSR0ZrFuRkjQjwVRu2T/oAluUGmqO0pPpfPOv3sYBqCoaPtNDrqG1sPAgvoLiaqsQ28PnTY3LeUFi9Y/ZXGHP7557cDu3sBOX0QD0gXeShb1ygh0j3pOe1ynjtyJjw/BqQIL/VSo6CVE+3UxxxLCZ15t6sfFIbKkgwYjtXayFutu1me9VDwuwYE/7zJFnwAgjh/Wz7gQlwZya6xrGvxHVLT71WDyEWtQKf8EwACnHe1DjiLBzIydw7EmoHK5hIgj320khbBfa8e8hqPPtW/tHFjF7+MT4xZzXcw8B54XrZoaDMdAOJF2EVyzHryxqJ3bzJNcu7eg3HkusT/tukNbBF1Hmf82gIT3IZ1HYPqRmd7+FaXdsc4VEoi2ZMBAc4CrdTwrtnhe8IBhZkUsbNLRS25fkhxOyd2ip2PYgZqXK4qD1cmRdivdqNdL/1HfHKFkuoR/GXTgXhzSPd+xcLW98TX8jvbN1qRbs2pRurGK8S7b6NzG84fxnLRUhGBgDraM1H32ZE1Hpq1UMkpkRPd4yUSs4iY=
  file_glob: true
  file:
  - "**/target/*.jar"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: cqw/jT7GAzpUqP6ziyoXQ+3oxz8Ts02w4xxOCrM/FPmCjUiiWOwPAXIDLHIxXbo/pukORgfbJf6HRp9y8TkpHk09bRCurFKReizcscT/rXeX5YLKieMl9o93C0nd+gyxXItwoWDN/7y03xfbVYoHatvHlrDd+d6NUsdVLMU5Jb5/vBsZz8AzM+Jn8QcxtkdUn/zbchdlVHl6IT6FXeUoUChK+VRAw3/z9wJlBiPTlkYhDnFBPOD59MP2CINn8ce0cP10IAG6P/I/drXsJJSZO7uFTfG4g0FIyS0XRbZrEoDLYJUZ9nU3DIK4YSm9SPZXFLOMmGS3s4dMVLxZmNbFlep0VCa8ODMBLbWqVh5n1VR9tkOQIBC+6feeL6r6C5rRMvH+buVek2PiOTWFlcyVaOydTcX9vzATmljPh+a9dHAgPwz+W/MM6XYrTLNKpQGCv01DBWlmUwNHaADmNJCMk0QGcZNEfbsVzFX09tgcM4wSUWHKdnJ9v3fmu1K1+8m67f2IlHWZb/nt6xgK3yTRKQ7Ys4ASflQ0Ns/yw+51fgxSGy/OGtpj+KIQOKom5lA02zfm+SQFK+dqSZ0/G/0NZAOCGyrYduStyEyn7a9MgWI0YQfWcMon8MzMC4g+F+c6etdfkPDGBK4wPfydUtdQzWDEiDSbwQHJD3V3viw18WY=
  - secure: NRTr/qtVV/SqghPq6iJ6p6aNmBSmnoCR/khV7Mv3uOsTIlg/nlUG7XkutaiXBjKSl+SjNFmumSDo76rtQK6NzsFTQWbfdlx9VLaPr8Zxbcjnpxq0s0deMaPlMNkcVJwX7jo1zwhxaQwN0iK8vZfsMSv5eEG/7mSKDUVDcQHuWl8P8LX4TMKPYhtewTLl2N71iI1YtCS57/frnGem19q4gdW7Zh0CcW1mJ3KI5A1VjgOV24O81RDyneRRkF+7DqnLQrO0/7VeHPR+MIFD1dBPur1q78j7g7rxrvo+JH5o0M1yyKv5PCAtfI7Opddeb3yPnBbkeXCDE9nLPXcbaTQzAJZkMYI0lex0EHuOvDoyxhKxRdRruyMbuslRhzUQcr0qKGZAyRiv1ptLKDUntOZX57bdwy63xEEoq0RBI1yGIr99+2PxgnJjIBZn6GUAdbHdpSr8CxMkNUWHgTB7nV+EONJHbr3x1ShFGxx/6Z319qUMd3ZdpVUhBCyjaWQEIlSC8Myy33V7NDdQQQ+JHClP+aVoAzByOJ5/QSCIeuO5hHtQ8PcoHZFTawNLIwSI525kUOPEEtCvKlI9p6bfH1Guzh8lAfM+iJwTjGJ2QUZg2jhB8//v46ChCAUOeFXEmJ2ZJ+YO5jbtV+Yz15w8idzPoIbf8JnqpaM7TI6W6BmF4uY=
