language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

addons:
  apt:
    packages:
      - libturbojpeg

before_script:
  - wget https://github.com/uclouvain/openjpeg/releases/download/v2.3.0/openjpeg-v2.3.0-linux-x86_64.tar.gz -O /tmp/openjpeg.tar.gz
  - tar -xvf /tmp/openjpeg.tar.gz
  - export LD_LIBRARY_PATH=$PWD/openjpeg-v2.3.0-linux-x86_64/lib:$LD_LIBRARY_PATH
